Repository LiemQLe/liemsniffers-fortune-cookies, pull requests merged in 2025-08, with the labels that each got.

#11 Exposed dockerfiles
  backend/Dockerfile
  frontend/Dockerfile
Labels: enhancement

#17 Update Dockerfile
  backend/Dockerfile
  frontend/Dockerfile
Labels: documentation

#18 Docker compose dependency fix
  docker-compose.yml
Labels: enhancement

#21 Update main.yml
  .github/workflows/main.yml
Labels: enhancement, pipeline

#24 Proper Tagging for docker in pipeline
  .github/workflows/main.yml
Labels: enhancement, pipeline

#25 Update main.yml
  .github/workflows/main.yml
Labels: enhancement, pipeline

#26 Push images#22
  .github/workflows/main.yml
Labels: enhancement, pipeline

#30 Created deployments and services
  deplpoyments/backend.yml
  deplpoyments/frontend.yml
Labels: enhancement

#34 Deployments name change
  deployments/backend.yml
  deployments/frontend.yml
Labels: invalid

#41 Rollout when deploying to refresh images
  .github/workflows/main.yml
Labels: bug, pipeline

#44 Fixed
  .github/workflows/main.yml
Labels: bug, pipeline

#45 Database
  backend/Dockerfile
  deployments/redis.yml
  docker-compose.yml
Labels: enhancement
